/**
 * Timeline export — turn a route's dated steps into things a student can take
 * away offline: an `.ics` calendar file and a printable (Save-as-PDF) document.
 *
 * Everything here runs in the browser (it touches Blob / document / iframe) and
 * is called from client `onClick` handlers. Dates stay deliberately coarse: the
 * spec only ever gives us a relative `offsetMonths` per step, so calendar events
 * are all-day, pinned to the 1st of the computed month, and every one carries an
 * "approximate — verify" note. Calendars are also capped to the next two years,
 * because a five-year, month-fuzzy reminder is noise, not help.
 */

import type { JourneyStep } from "./types";
import { computeTargetMonth } from "./timeline";

/** Steps further out than this are dropped from the *calendar* (kept in print). */
export const CALENDAR_HORIZON_MONTHS = 24;

/** Localised, presentation-layer strings the builders need. */
export interface ExportLabels {
  /** "Approximate timing — verify exact dates on official sites before acting." */
  approxNote: string;
  /** Marker appended to optional steps, e.g. "Optional". */
  optional: string;
  /** Heading shown above an either/or fork, e.g. "Either / or — pick one". */
  eitherOr: string;
  /** Note added when later steps were trimmed from the calendar. */
  cappedNote: string;
  /** Small footer line, e.g. "Generated by My Career Journey". */
  generatedBy: string;
}

/** Identifies the timeline being exported (for titles, filenames and UIDs). */
export interface ExportContext {
  career: string;
  routeName: string;
  routeId: string;
}

// ---------------------------------------------------------------------------
// .ics calendar
// ---------------------------------------------------------------------------

/** Escape a value for an iCalendar text field (RFC 5545 §3.3.11). */
function icsEscape(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\r?\n/g, "\\n");
}

/** Fold a content line to <=75 octets with CRLF + leading space (RFC 5545 §3.1). */
function foldLine(line: string): string {
  if (line.length <= 75) return line;
  const chunks: string[] = [];
  let rest = line;
  chunks.push(rest.slice(0, 75));
  rest = rest.slice(75);
  while (rest.length > 0) {
    chunks.push(" " + rest.slice(0, 74));
    rest = rest.slice(74);
  }
  return chunks.join("\r\n");
}

/** YYYYMMDD for an all-day DATE value. `month` is 0-indexed. */
function icsDate(year: number, month: number, day: number): string {
  const mm = String(month + 1).padStart(2, "0");
  const dd = String(day).padStart(2, "0");
  return `${year}${mm}${dd}`;
}

/** Current UTC timestamp as YYYYMMDDTHHMMSSZ for DTSTAMP. */
function icsStamp(now = new Date()): string {
  return now.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
}

/** True when this step is one side of an either/or fork. */
function inFork(step: JourneyStep, forkIds: Set<string>): boolean {
  return forkIds.has(step.id);
}

/** Collect the ids of every step that participates in a fork. */
function forkStepIds(steps: JourneyStep[]): Set<string> {
  const ids = new Set<string>();
  for (const s of steps) {
    if (s.alternativeTo !== undefined) {
      ids.add(s.id);
      ids.add(s.alternativeTo);
    }
  }
  return ids;
}

/**
 * Build an iCalendar document for a route's steps. Returns the `.ics` text plus
 * whether any steps were trimmed for being beyond the two-year horizon (so the
 * UI can hint at it). Each step becomes one all-day event on the 1st of its
 * computed month, carrying the verify-first note.
 */
export function buildTimelineIcs(
  steps: JourneyStep[],
  anchor: string,
  ctx: ExportContext,
  labels: ExportLabels,
): { ics: string; capped: boolean } {
  const stamp = icsStamp();
  const forkIds = forkStepIds(steps);

  // Calendar gets near-term steps only; print keeps the full plan.
  const withinHorizon = steps.filter((s) => s.offsetMonths <= CALENDAR_HORIZON_MONTHS);
  const capped = withinHorizon.length < steps.length;

  const calDesc = capped ? `${labels.approxNote} ${labels.cappedNote}` : labels.approxNote;

  const lines: string[] = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//My Career Journey//Timeline//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    `X-WR-CALNAME:${icsEscape(`${ctx.career} — ${ctx.routeName}`)}`,
    `X-WR-CALDESC:${icsEscape(calDesc)}`,
  ];

  for (const step of withinHorizon) {
    const { year, month } = computeTargetMonth(anchor, step.offsetMonths);
    const start = icsDate(year, month, 1);
    const end = icsDate(year, month, 2); // DTEND is exclusive for all-day events.

    let summary = step.title;
    if (step.optional) summary += ` (${labels.optional})`;

    const descParts = [step.description];
    if (inFork(step, forkIds)) descParts.push(labels.eitherOr);
    descParts.push(labels.approxNote);
    const description = descParts.join("\n\n");

    lines.push(
      "BEGIN:VEVENT",
      `UID:${ctx.routeId}-${step.id}-${stamp}@career-journey`,
      `DTSTAMP:${stamp}`,
      `DTSTART;VALUE=DATE:${start}`,
      `DTEND;VALUE=DATE:${end}`,
      `SUMMARY:${icsEscape(summary)}`,
      `DESCRIPTION:${icsEscape(description)}`,
      "TRANSP:TRANSPARENT",
      "END:VEVENT",
    );
  }

  lines.push("END:VCALENDAR");

  // Fold every line and join with CRLF, as required by RFC 5545.
  const ics = lines.map(foldLine).join("\r\n") + "\r\n";
  return { ics, capped };
}

// ---------------------------------------------------------------------------
// Download / print helpers
// ---------------------------------------------------------------------------

/** Make a string safe for use as a download filename. */
export function safeFilename(name: string): string {
  return name
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .toLowerCase()
    .slice(0, 60) || "timeline";
}

/** Trigger a client-side download of `content` as a file. */
export function downloadTextFile(filename: string, mime: string, content: string): void {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoke on the next tick so the download has a chance to start.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Print an HTML document via a hidden iframe (no popup, so it survives popup
 * blockers). The iframe is removed once the print dialog closes. The caller is
 * responsible for escaping any user/content strings baked into `html`.
 */
export function printHtmlDocument(html: string): void {
  const iframe = document.createElement("iframe");
  iframe.setAttribute("aria-hidden", "true");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  document.body.appendChild(iframe);

  const doc = iframe.contentWindow?.document;
  if (!doc) {
    iframe.remove();
    return;
  }
  doc.open();
  doc.write(html);
  doc.close();

  const win = iframe.contentWindow;
  if (!win) {
    iframe.remove();
    return;
  }

  const cleanup = () => setTimeout(() => iframe.remove(), 500);
  win.addEventListener("afterprint", cleanup, { once: true });

  // Give the iframe a beat to lay out before invoking print.
  win.onload = () => {
    win.focus();
    win.print();
  };
  // Fallback for browsers that don't fire load on a written-to iframe.
  setTimeout(() => {
    try {
      win.focus();
      win.print();
    } catch {
      iframe.remove();
    }
  }, 250);
}

// ---------------------------------------------------------------------------
// Printable HTML
// ---------------------------------------------------------------------------

/** Escape a string for safe interpolation into HTML. */
export function htmlEscape(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Shared <style> + page chrome for printable documents. */
function printShell(title: string, bodyHtml: string): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${htmlEscape(title)}</title>
<style>
  * { box-sizing: border-box; }
  body {
    font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Arial, "Noto Sans", sans-serif;
    color: #1c1917; margin: 0; padding: 28px; line-height: 1.5;
  }
  h1 { font-size: 22px; margin: 0 0 2px; }
  h2 { font-size: 15px; margin: 24px 0 8px; }
  .sub { color: #b45309; font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: .04em; }
  .note { color: #78716c; font-size: 12px; margin: 6px 0 0; }
  ol.steps { list-style: none; margin: 12px 0 0; padding: 0; }
  ol.steps > li { display: flex; gap: 12px; padding: 0 0 14px; }
  .period { width: 72px; flex: none; font-weight: 700; font-size: 12px; color: #44403c; padding-top: 2px; }
  .body { flex: 1; min-width: 0; border-left: 2px solid #e7e5e4; padding: 0 0 0 12px; }
  .title { font-weight: 700; }
  .type { color: #b45309; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; }
  .desc { color: #44403c; font-size: 13px; margin: 3px 0 0; }
  .tag { display: inline-block; font-size: 10px; font-weight: 700; text-transform: uppercase;
         letter-spacing: .04em; background: #f5f5f4; color: #57534e; border-radius: 999px; padding: 1px 8px; margin-left: 6px; }
  .fork { background: #f5f3ff; border: 1px dashed #c4b5fd; border-radius: 10px; padding: 8px 10px; }
  .fork-head { color: #6d28d9; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .04em; }
  .line { display: block; border-bottom: 1px solid #d6d3d1; height: 26px; margin-top: 4px; }
  .disclaimer { background: #fefce8; border-radius: 10px; padding: 12px 14px; margin-top: 24px; font-size: 12px; color: #713f12; }
  .disclaimer ul { margin: 6px 0 0; padding-left: 18px; }
  /* AI-generated/unverified banner — deliberately prominent (thick amber border,
     bold title, printed in colour) so it can't read as a footnote. */
  .unverified { background: #fffbeb; border: 2px solid #f59e0b; border-radius: 10px;
    padding: 12px 14px; margin: 0 0 18px; color: #7c2d12;
    -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .unverified .uv-title { font-weight: 700; font-size: 14px; }
  .unverified .uv-body { font-size: 13px; margin-top: 2px; }
  footer { margin-top: 28px; color: #a8a29e; font-size: 11px; border-top: 1px solid #e7e5e4; padding-top: 10px; }
  @media print { body { padding: 0; } @page { margin: 16mm; } }
</style>
</head>
<body>
${bodyHtml}
</body>
</html>`;
}

/** A single step rendered for the printable timeline. */
export interface PrintStep {
  /** Coarse period label, e.g. "Mid 2026". */
  period: string;
  title: string;
  type: string;
  description: string;
  optional: boolean;
  /** First step of a fork → render the "either/or" wrapper opens here. */
  forkStart: boolean;
  /** Subsequent fork alternative (a sibling within the same fork). */
  forkMember: boolean;
}

/** Build a printable HTML document for a route's full (uncapped) timeline. */
export function buildTimelinePrintHtml(
  printSteps: PrintStep[],
  ctx: ExportContext,
  labels: ExportLabels,
  disclaimers: string[],
  headings: { forCareer: string; timeline: string; important: string },
  /** When set, a prominent AI-generated/unverified banner is printed at the top. */
  unverifiedBanner?: { title: string; body: string },
): string {
  const stepsHtml = printSteps
    .map((s) => {
      const optionalTag = s.optional
        ? `<span class="tag">${htmlEscape(labels.optional)}</span>`
        : "";
      const forkHead = s.forkStart
        ? `<div class="fork-head">${htmlEscape(labels.eitherOr)}</div>`
        : "";
      const inner = `${forkHead}<div class="title">${htmlEscape(s.title)}${optionalTag}</div>
        <div class="type">${htmlEscape(s.type)}</div>
        <p class="desc">${htmlEscape(s.description)}</p>`;
      const body = s.forkStart || s.forkMember
        ? `<div class="fork">${inner}</div>`
        : inner;
      return `<li><div class="period">${htmlEscape(s.period)}</div><div class="body">${body}</div></li>`;
    })
    .join("\n");

  const disclaimersHtml =
    disclaimers.length > 0
      ? `<div class="disclaimer"><strong>${htmlEscape(headings.important)}</strong>
         <ul>${disclaimers.map((d) => `<li>${htmlEscape(d)}</li>`).join("")}</ul></div>`
      : "";

  const bannerHtml = unverifiedBanner
    ? `<div class="unverified"><div class="uv-title">⚠️ ${htmlEscape(unverifiedBanner.title)}</div><div class="uv-body">${htmlEscape(unverifiedBanner.body)}</div></div>`
    : "";

  const body = `
  ${bannerHtml}
  <p class="sub">${htmlEscape(headings.forCareer)}</p>
  <h1>${htmlEscape(ctx.career)}</h1>
  <h2>${htmlEscape(ctx.routeName)} — ${htmlEscape(headings.timeline)}</h2>
  <p class="note">${htmlEscape(labels.approxNote)}</p>
  <ol class="steps">${stepsHtml}</ol>
  ${disclaimersHtml}
  <footer>${htmlEscape(labels.generatedBy)}</footer>`;

  return printShell(`${ctx.career} — ${ctx.routeName}`, body);
}

/** A blank-line plan section for the "plan it yourself" printable. */
export interface PrintPlanSection {
  heading: string;
  intro?: string;
  /** Each becomes a labelled blank line to write on. */
  blanks?: string[];
  /**
   * Labelled entries that carry whatever the user typed: a filled value is
   * printed as text; an empty one falls back to a blank line to write on. This
   * is how the download/print reflects the values already entered on the page.
   */
  fields?: { label: string; value: string }[];
  /** Each becomes a plain numbered list item (the research guide). */
  items?: string[];
}

/** Build a printable, fill-in-on-paper version of the "plan it yourself" page. */
export function buildPlanPrintHtml(
  title: string,
  intro: string,
  sections: PrintPlanSection[],
  generatedBy: string,
): string {
  const sectionsHtml = sections
    .map((sec) => {
      const introHtml = sec.intro ? `<p class="note">${htmlEscape(sec.intro)}</p>` : "";
      let listHtml = "";
      if (sec.fields) {
        // A typed value prints as text; an empty field becomes a blank line.
        listHtml = `<ol class="steps">${sec.fields
          .map((f) => {
            const value = f.value.trim();
            const filled = value
              ? `<p class="desc">${htmlEscape(value)}</p>`
              : `<span class="line"></span>`;
            return `<li><div class="body"><div class="title">${htmlEscape(
              f.label,
            )}</div>${filled}</div></li>`;
          })
          .join("")}</ol>`;
      } else if (sec.blanks) {
        listHtml = `<ol class="steps">${sec.blanks
          .map(
            (b) =>
              `<li><div class="body"><div class="title">${htmlEscape(
                b,
              )}</div><span class="line"></span></div></li>`,
          )
          .join("")}</ol>`;
      } else if (sec.items) {
        listHtml = `<ol style="padding-left:18px;color:#44403c;font-size:13px;">${sec.items
          .map((i) => `<li style="margin:4px 0;">${htmlEscape(i)}</li>`)
          .join("")}</ol>`;
      }
      return `<h2>${htmlEscape(sec.heading)}</h2>${introHtml}${listHtml}`;
    })
    .join("\n");

  const body = `
  <h1>${htmlEscape(title)}</h1>
  <p class="note">${htmlEscape(intro)}</p>
  ${sectionsHtml}
  <footer>${htmlEscape(generatedBy)}</footer>`;

  return printShell(title, body);
}
