"use client";

/**
 * Journey view (spec §journey-view). This page renders whatever the intake flow
 * just generated, handed over via sessionStorage; opened directly (e.g. the "see
 * a sample" link) it falls back to the bundled sample so the UI is viewable
 * offline. The bookmarkable, cache-backed variant lives at /journey/[slug].
 */

import { useEffect, useState } from "react";
import { sampleJourney } from "@/lib/sampleJourney";
import { loadStoredJourney } from "@/lib/generate/client";
import type { JourneyStatus } from "@/lib/generate/types";
import type { Journey } from "@/lib/types";
import { JourneyView } from "@/components/journey/JourneyView";

export default function JourneyPage() {
  // Prefer a journey generated by the intake flow (handed over via
  // sessionStorage); fall back to the bundled sample so the page still renders
  // when opened directly.
  const [served, setServed] = useState<{
    journey: Journey;
    status: JourneyStatus;
  } | null>(null);

  // Read sessionStorage only after mount: it doesn't exist during SSR, and
  // updating on mount (not in render) keeps server and first client render
  // identical, avoiding a hydration mismatch.
  useEffect(() => {
    const stored = loadStoredJourney();
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (stored) setServed({ journey: stored.journey, status: stored.status });
  }, []);

  const journey = served?.journey ?? sampleJourney;
  // The sample isn't a verified default, but it's curated, so don't stamp it.
  const status: JourneyStatus | null = served?.status ?? null;

  return <JourneyView journey={journey} status={status} />;
}
