"use client";

/**
 * Journey view (spec §journey-view). This page renders whatever the intake flow
 * just generated, handed over via sessionStorage; opened directly (e.g. the "see
 * a sample" link) it falls back to the bundled sample so the UI is viewable
 * offline. The bookmarkable, cache-backed variant lives at /journey/[slug].
 *
 * A "Regenerate" action (open to everyone, rate-limited at the route) forces a
 * fresh live plan, rebuilt from the current journey's non-personal cache key.
 */

import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { sampleJourney } from "@/lib/sampleJourney";
import {
  GenerationFailedError,
  loadStoredJourney,
  profileFromSlug,
  requestJourneyStream,
  storeJourney,
} from "@/lib/generate/client";
import { cacheKeyToSlug } from "@/lib/generate/cacheKey";
import { modelDisplayName } from "@/lib/generate/modelLabel";
import { useI18n } from "@/lib/i18n/I18nProvider";
import type { JourneyStatus } from "@/lib/generate/types";
import type { Journey } from "@/lib/types";
import { JourneyView } from "@/components/journey/JourneyView";
import GeneratingChat from "@/components/intake/GeneratingChat";

export default function JourneyPage() {
  const { t, locale } = useI18n();
  const router = useRouter();

  // Prefer a journey generated by the intake flow (handed over via
  // sessionStorage); fall back to the bundled sample so the page still renders
  // when opened directly.
  const [served, setServed] = useState<{
    journey: Journey;
    status: JourneyStatus;
  } | null>(null);

  // While a regeneration streams, the chat-style progress view takes over.
  const [regenerating, setRegenerating] = useState(false);
  const [modelLabel, setModelLabel] = useState<string | null>(null);
  const [genError, setGenError] = useState<string | null>(null);
  const [genPrompt, setGenPrompt] = useState<string | null>(null);
  const [attempt, setAttempt] = useState(0);

  // Read sessionStorage only after mount: it doesn't exist during SSR, and
  // updating on mount (not in render) keeps server and first client render
  // identical, avoiding a hydration mismatch.
  useEffect(() => {
    const stored = loadStoredJourney();
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (stored) setServed({ journey: stored.journey, status: stored.status });
  }, []);

  const journey = served?.journey ?? sampleJourney;
  // The sample isn't a verified default, but it's curated, so don't stamp it.
  const status: JourneyStatus | null = served?.status ?? null;

  // Force a fresh live plan, rebuilt from this journey's non-personal cache key.
  // `regenerate` is recreated each render, so it closes over the current journey.
  async function regenerate() {
    const lang = journey.meta.studentProfile.language || locale;
    const slug = cacheKeyToSlug(journey.meta.cacheKey);
    const profile = profileFromSlug(slug, lang, new Date().toISOString().slice(0, 10));
    if (!profile) {
      // No usable cache key (shouldn't happen for a real plan): just retry view.
      return;
    }
    setGenError(null);
    setGenPrompt(null);
    setModelLabel(null);
    setRegenerating(true);
    setAttempt((n) => n + 1);
    try {
      const payload = await requestJourneyStream(
        profile,
        (event) => {
          if (event.model) setModelLabel(modelDisplayName(event.provider, event.model));
        },
        { refresh: true },
      );
      storeJourney(payload);
      setServed({ journey: payload.journey, status: payload.status });
      setRegenerating(false);
    } catch (err) {
      setGenError(err instanceof Error ? err.message : t("intake.done.generateError"));
      if (err instanceof GenerationFailedError && err.externalPrompt) {
        setGenPrompt(err.externalPrompt);
      }
    }
  }

  if (regenerating) {
    return (
      <GeneratingChat
        key={attempt}
        modelLabel={modelLabel}
        error={genError}
        externalPrompt={genPrompt}
        onRetry={regenerate}
        onStartOver={() => {
          setRegenerating(false);
          router.push("/intake");
        }}
      />
    );
  }

  return <JourneyView journey={journey} status={status} onRegenerate={regenerate} />;
}
